title: Xinyi Qiu # your name (or website title) here
logo: "/images/Personal Photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Master of City Planning candidate, 2021
  <br><br>
  Concentrated in Sustainable Transportation and Infrastructure Planning
  <br><br>
  Contributed to the study of emerging transportation technology, and transit equity
  <br><br>
  <a href="https://www.linkedin.com/in/xinyi-qiu16">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

